# Generated by Django 5.1.2 on 2024-10-18 07:02

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_emprunt',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
