# Generated by Django 5.1.2 on 2024-11-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_emprunteur_bloque_emprunteur_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunteur',
            name='auteur',
        ),
        migrations.AddField(
            model_name='emprunteur',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
    ]
